### ISSUE TITLE
front end blip 

### ISSUE THREAD

**Issue by lucasverra** [csev/wa4e#2]
1 img > 10^3 words 

![image](https://user-images.githubusercontent.com/11323803/29575964-7c955210-8766-11e7-9435-f2ab7a053eb4.png)

Cheers !

**Comment by Steve-Z** [comment]
I noticed that as well. I think it can be "fixed" by changing inline style tags for html. Replace
 `.card {
        border: 1px solid black;
        margin: 5px;
        padding: 5px;
        min-height: 8em;
    }`
with
`.card {
    display: inline-block;
    width: 160px;
    height: 125px;
    padding: 5px;
    margin: 12px;
    border: 1px solid black;  
}`
I have only tested this locally on Firefox 54, but seems to render correctly; although width seems to be overridden by ???

**Comment by csev** [comment]
Can you fix it here?  Then you get credit for the fix.

https://github.com/tsugiproject/tsugi-php/blob/master/src/UI/Lessons.php

**Comment by Steve-Z** [comment]
I edited ".card { … }" in the style tag. Works on my two browsers, FF 55 and Safari 11. Maybe you want to test it on other browsers and platforms. FWIW current version displays fine on my iPhone6 — the cards stack vertically.

Hope this works.

Best,

Steve

**Comment by lucasverra** [comment]
fixed by @Steve-Z , just checked in safari, latest chrome and latest firefox.
Cheers to both of you ! 
@csev ping me when in Paris !
