### ISSUE TITLE
PHP: get_magic_quotes_gpc() is deprecated

### ISSUE THREAD

**Issue by winkler-winsen** [csev/wa4e#25]
PHP informs:

> Deprecated:  Function get_magic_quotes_gpc() is deprecated in C:\MAMP\htdocs\phplearn\pdo\aa-error-check.php on line 18

```php
$magic = get_magic_quotes_gpc();
echo 'magic_quotes_gpc = ' . ($magic == 1 ? "On" : "Off") . "\n";
if ( get_magic_quotes_gpc() == 0 ) {
    echo("magic_quotes_gpc is set correctly...\n\n");
    $good ++;
} else {
    echo("WARNING: You need to edit your configuration file\n");
    echo("and set:\n\n");
    echo("magic_quotes_gpc = off\n\n");
}
```
https://github.com/csev/wa4e/blob/7bb454d89bec060f482dc2bdd2cb27a09bc265b9/code/pdo/aa-error-check.php#L18
https://github.com/csev/wa4e/blob/7bb454d89bec060f482dc2bdd2cb27a09bc265b9/code/pdo/aa-error-check.php#L20

Using MAMP 4.2.0.23973
- PHP 7.4.1

**Comment by csev** [comment]
Thanks - fixed in 755f0f2e769155179e6dc4296b4d27f53860e32e
