### ISSUE TITLE
MySQL: change Warning: #1287 change GRANT to CREATE USER (deprecated) 

### ISSUE THREAD

**Issue by winkler-winsen** [csev/wa4e#26]
https://github.com/csev/wa4e/blob/6a5fe20b1693c17d9b186ed12ac34d7ba1383a44/code/pdo/NOTES.txt#L4
https://github.com/csev/wa4e/blob/6a5fe20b1693c17d9b186ed12ac34d7ba1383a44/code/pdo/NOTES.txt#L5

split into two actions "CREATE USER" and "GRANT"

**Comment by csev** [comment]
Fixed in cf576876a77c264a88348022ec7c6891ad2bb0ed

**Comment by csev** [comment]
Thanks
