### ISSUE TITLE
A new composer dependency (or an updated one) requires PHP version >=7.4.0. Website non-functional

### ISSUE THREAD

**Issue by PC-DUSS** [csev/wa4e#45]
I  was going through the WA4E course just now, and on page refresh the website is now only replying an error message, saying that a composer dependency requires PHP >=7.4.0  . In comparison, the DJ4E website is working just fine.

**Comment by PC-DUSS** [comment]
![wa4e_screenshot](https://user-images.githubusercontent.com/80858807/159963850-7a313081-e736-43bb-9955-0d179abd787d.png)

**Comment by csev** [comment]
Thanks so much - I just fixed it.   Thanks for the quick bug report.

**Comment by csev** [comment]
Your timing was perfect - I almost left my laptop after putting in a small fix that broke it - and your issue appeared in my email - I immediately knew I messed up in a really tiny way and how to fix it.  I am glad you are enjoying the course.
